services:
  pixhub:
    build: .
    container_name: pixhub
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - /vol1/1000/resources:/app/resources
    restart: unless-stopped
