services:
  pixhub:
    build: .
    container_name: pixhub
    ports:
      - "${PORT}:3000"
    volumes:
      - ./data:/app/data"
      - "${RESOURCES}:/app/resources"
    restart: unless-stopped
